<%@ Page Language="VB" AutoEventWireup="false" CodeFile="Tree.aspx.vb" Inherits="Tree" %>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head id="Head1" runat="server">
	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
	<link href="css/css.css" rel="stylesheet" type="text/css" />
	<title>功能選項清單</title>
</head>
<body style="margin: 10pt 0pt 0pt 0pt">
	<form id="form1" runat="server">
	<div>
		<asp:TreeView ID="tv_func" runat="server" EnableClientScript="False" ExpandDepth="1"
			AutoGenerateDataBindings="False" LineImagesFolder="~/Images/TreeLineImages" CssClass="text11pt"	Width="100%">
			<ParentNodeStyle CssClass="text11pt" Width="100%" />
			<SelectedNodeStyle CssClass="text11pt" Width="100%" />
			<RootNodeStyle CssClass="text11pt" Width="100%" />
			<NodeStyle CssClass="text11pt" Width="100%" />
			<LeafNodeStyle CssClass="text11pt" Width="100%" />
		</asp:TreeView>
	</div>
	</form>

	<script language="javascript" type="text/javascript">
		function chgcont(murl)
		{
			var frameobj;
			var now = new Date();
			var timestamp = now.getMinutes() + now.getSeconds() + now.getMilliseconds();

			frameobj = top.document.getElementById("mcontent");

			// 加上 timestamp 時間，以避開 IE 的 Cache
			if (murl.indexOf("?") > 0)
				murl += "&timestamp=" + timestamp;
			else
				murl += "?timestamp=" + timestamp;
			frameobj.src = murl;
		}
	</script>

</body>
</html>
